### ISSUE TITLE
Regression on dll import function names bug for ws2_32.dll[XX]

### ISSUE THREAD

**Issue by Maijin** [radare/radare2#2271]
[  ]  1  import_names: dll import function names bug for ws2_32.dll[XX]
    Command:  /usr/local/bin/radare2 -e cfg.plugins=false -e scr.color=0 -N -q -i /tmp/r2-regressions//import_names-rad.6e2ISl   ../../bins/pe/Lab05-01.dll > /tmp/r2-regressions//import_names-out.G76uC8 2> /tmp/r2-regressions//import_names-err.i3Yx9m
    File: ../../bins/pe/Lab05-01.dll
    Script: ii~&WS2_32,ordinal=052
    Diff: --- /tmp/r2-regressions//import_names-exp.DU9RZn	2015-03-31 02:35:56.634967034 +0000
    +++ /tmp/r2-regressions//import_names-out.G76uC8	2015-03-31 02:35:56.669965337 +0000
    @@ -1 +1 @@
    -ordinal=052 plt=0x000163cc bind=NONE type=FUNC name=WS2_32.dll_gethostbyname
    +ordinal=052 plt=0x000163cc bind=NONE type=FUNC name=qqWS2_32.dll_Ordinal_52

**Comment by skuater** [comment]
The problem is  r2 cant  find the .sdb with the definition of the ws_32.dll. 
U can put the file locate at "\libr\bin\d\dll\WS2_32.sdb" into:
"share/radare2/"R2_VERSION"/format/dll/" (for windows)
or
R2_PREFIX"/share/radare2/" R2_VERSION"/format/dll/" (for linux)

And the problem its solved. If u are working in linux doing the TESTs ,be sure to tell to r2 where locate these  .sdb files.

Let me know if u have any trouble. Regards.

**Comment by radare** [comment]
@maijin please confirm/test

**Comment by radare** [comment]
maybe `make install` does not installs the dll.sdb files in a proper way, or maybe symstall does it different or something

**Comment by radare** [comment]
This is the output of travis (maybe related)

```
$ sudo make install > /dev/null
/usr/bin/install: omitting directory `doc/3D'
/usr/bin/install: omitting directory `doc/node.js'
/usr/bin/install: omitting directory `doc/pdb'
/usr/bin/install: omitting directory `doc/sandbox'
cp: omitting directory `dll'
```

**Comment by Maijin** [comment]
Passing the PE  tests from XX->BR for adding on TravisCI

**Comment by XVilka** [comment]
Is this still reproducible?

**Comment by Maijin** [comment]
@XVilka yep https://travis-ci.org/radare/radare2/jobs/84052723#L381

**Comment by radare** [comment]
fixed

**Comment by radare** [comment]
please confirm. @ret2libc ?

**Comment by Maijin** [comment]
I just said it wasn't fix, why closing ?

**Comment by radare** [comment]
becaus i fixed the reloc test

**Comment by Maijin** [comment]
But the problem is still present on TravisCI, so it's not fixed

**Comment by radare** [comment]
thats why i respected your reopen <3

**Comment by Maijin** [comment]
oki :+1:

**Comment by radare** [comment]
This should be fixed now. can you retest?

**Comment by Maijin** [comment]
@radare nop https://travis-ci.org/radare/radare2/jobs/85531215#L3240

**Comment by radare** [comment]
this happens because the libr/bin/d files are wrongly installed.

it works fine in my machine, but maybe there’s a problem in the make install or in make symstall

**Comment by Maijin** [comment]
Since the CI is currently down, no proof of that working yet
