### ISSUE TITLE
Mini-graph overlap with disassembly 

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#3015]
There is space that is not used 

<img width="1434" alt="captura de pantalla 2015-07-28 a las 16 36 56" src="https://cloud.githubusercontent.com/assets/3474042/8934223/ef1c357a-3546-11e5-826f-f1a4f7cff923.png">

**Comment by radare** [comment]
Just scroll the canvas with HJKL

**Comment by radare** [comment]
Maybe we can center the graph in a better way..

**Comment by ret2libc** [comment]
It should be fixed. @alvarofe please confirm ;)

**Comment by alvarofe** [comment]
I still get the this but with HJKL I can move the canvas

<img width="1548" alt="captura de pantalla 2015-08-09 a las 16 06 05" src="https://cloud.githubusercontent.com/assets/3474042/9155209/9bafdf18-3eb0-11e5-9f3d-97201cadefa3.png">

**Comment by alvarofe** [comment]
It's fixed sorry I was running an old r2 version ;)
