### ISSUE TITLE
Issue with target 'capstone-sync' 

### ISSUE THREAD

**Issue by LuchoEskimo** [radare/radare2#3120]
My OS is Fedora 22. I downloaded the latest version of radare2, but by using `sudo ./sys/install.sh`, I got the following error: 

    Makefile:206: recipe for target 'capstone-sync' failed
    gmake[1] : *** [capstone-sync] Error 127

**Comment by alvarofe** [comment]
I get the same in openbsd
<img width="1552" alt="captura de pantalla 2015-08-19 a las 16 25 20" src="https://cloud.githubusercontent.com/assets/3474042/9358939/ee40b334-468e-11e5-835d-38d911f99277.png">

**Comment by XVilka** [comment]
Probably because of 43f71e0c9281a2e2f54ad178b19805506dd3fd51

**Comment by radare** [comment]
this is a known bug from the 0.9.9 release. if you have problems with git just rm -rf shlr/capstone and sys/install.sh should be fine

**Comment by LuchoEskimo** [comment]
And could we fix it without deleting shlr/capstone ?

**Comment by radare** [comment]
if you remove this directory, capstone will be fetched again. im trying to reproduce the issue but it seems to be fine for me. are you using git or 0.9.9?

**Comment by alvarofe** [comment]
I just did `git clean -xfd`, `sudo make clean` and then make worked properly

**Comment by mrpink17** [comment]
I had this issue too.
After removing shlr/capstone directory i got it working changing line 12 in shlr/Makefile from:
CS_URL=$(GIT_PREFIX)github.com/aquynh/capstone.git
to
CS_URL=https://github.com/aquynh/capstone.git
I did not investigate why $(GIT_PREFIX) was not working for me

**Comment by radare** [comment]
GIT_PREFIX comes from global.mk which is like this:
```
ifndef USE_GIT_URLS
GIT_PREFIX=https://www.
else
GIT_PREFIX=git://
endif
```

are you using gmake?

**Comment by LuchoEskimo** [comment]
I've tried to remove the directory, but every time it is redownloaded, and the same error occurs... I'm using the git version.
Also, neither alvarofe's nor mrpink17's solution works: the former issue other errors when calling `sudo make clean`, while there isn't any difference when I use the latter.

**Comment by mrpink17** [comment]
@radare:
I am using make, not gmake

**Comment by radare** [comment]
Always use gmake on BSD systems

**Comment by mrpink17** [comment]
I think global.mk is wrong. line GIT_PREFIX=https://www. should be GIT_PREFIX=https://
Then git clone works for captstone repository.

**Comment by radare** [comment]
Please send a pullreq

**Comment by mrpink17** [comment]
done

**Comment by LuchoEskimo** [comment]
The pullreq from mrpink17 didn't solve the issue, but if I use `./configure; make all; make install` instead of the classical `./sys/install`, there's no problem anymore

**Comment by radare** [comment]
if you do this then you will have 2 different installations of r2 in 2 different paths, using the system capstone which is probably old.

i cant reproduce any issue with capstone-sync with sys/install.sh

**Comment by LuchoEskimo** [comment]
Finally, I updated my local version of your repo (which was approximately 1 hour old...) and the issue isn't reproducible anymore...
