### ISSUE TITLE
Remote debugging buffer size problem when connecting to gdbserver

### ISSUE THREAD

**Issue by itsbriany** [radare/radare2#3129]
Hi, I am having buffer problems with remote debugging. I am connecting to gdbserver on localhost:1234 with r2. I am running Ubuntu Linux 14.04 LTS x86_64.

Here is my version of gdbserver:

```bash
itsbriany@linux:~/Playground/infosec/c++$ gdbserver --version
GNU gdbserver (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-linux-gnu"
```

My last build of r2 was two days ago.

Here is my command to starting gdbserver:
```bash
itsbriany@linux:~/Playground/infosec/c++$ gdbserver localhost:1234 a.out 
Process a.out created; pid = 2730
Listening on port 1234
Remote debugging from host 127.0.0.1
```

Here is my output when connecting to gdbserver with r2:

```bash
itsbriany@linux:~/Playground$ r2 -D gdb gdb://localhost:1234
Debugging pid = 6, tid = 6 now
XWJSTEP TOFALSE
Attached debugger to pid = 22758384, tid = 1
Debugging pid = 22758384, tid = 1 now
r_debug_gdb_reg_read: small buffer 536 vs 544
r_debug_gdb_reg_read: small buffer 536 vs 544
 -- Now featuring NoSQL!
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> aa
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> iz

r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> iI

r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]>
```

I can still print disassembly with the command: "pd", but I cannot get any information on the binary with commands such as "iz", "iI", etc.

Is this buffer problem a bug or am I not properly connecting to gdbserver?

**Comment by XVilka** [comment]
> two days ago
Too old, should be fixed in master. Try to update your r2

**Comment by itsbriany** [comment]
I just updated my build with sys/install.sh, restarted gdbserver on localhost:1234, but I am still getting the same error.

```bash
itsbriany@linux:~$ r2 -D gdb gdb://localhost:1234
Debugging pid = 6, tid = 6 now
XWJSTEP TOFALSE
Attached debugger to pid = 31425904, tid = 1
Debugging pid = 31425904, tid = 1 now
r_debug_gdb_reg_read: small buffer 536 vs 544
r_debug_gdb_reg_read: small buffer 536 vs 544
 -- PEBCAK ERROR: Documentation not found.
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> aa
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> iI

r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> iz

r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> 
```

**Comment by radare** [comment]
Can you try specifying the -a x86 -b 32 (or whatever the arch/os pair is)?

Memory read/write works?

i commands doesnt show anything because the bin is not loaded into radare, you can import that with ob command. But also just use rabin like this:

.!rabin2 -rs a.out

Change s to get imports, symbols, sections.. Youcan add more than one.

Theres no support for retrieving symbols imformation from the remote gdb. Unless by using ob which is r2 who parses the bin by reading the process in nemory. But this is not going to always work because headers in memory are diferent than in disk and some info is lost.

**Comment by XVilka** [comment]
@radare 
Strange thing, because gdb register profile looks matching to the r2 one:

https://github.com/radare/radare2/blob/master/libr/debug/p/debug_gdb.c#L254

```
gdb$ maint print registers
 Name         Nr  Rel Offset    Size  Type            
 rax           0    0      0       8 int64_t         
 rbx           1    1      8       8 int64_t         
 rcx           2    2     16       8 int64_t         
 rdx           3    3     24       8 int64_t         
 rsi           4    4     32       8 int64_t         
 rdi           5    5     40       8 int64_t         
 rbp           6    6     48       8 *1              
 rsp           7    7     56       8 *1              
 r8            8    8     64       8 int64_t         
 r9            9    9     72       8 int64_t         
 r10          10   10     80       8 int64_t         
 r11          11   11     88       8 int64_t         
 r12          12   12     96       8 int64_t         
 r13          13   13    104       8 int64_t         
 r14          14   14    112       8 int64_t         
 r15          15   15    120       8 int64_t         
 rip          16   16    128       8 *1              
 eflags       17   17    136       4 i386_eflags     
 cs           18   18    140       4 int32_t         
 ss           19   19    144       4 int32_t         
 ds           20   20    148       4 int32_t         
 es           21   21    152       4 int32_t         
 fs           22   22    156       4 int32_t         
 gs           23   23    160       4 int32_t         
 st0          24   24    164      10 _i387_ext       
 st1          25   25    174      10 _i387_ext       
 st2          26   26    184      10 _i387_ext       
 st3          27   27    194      10 _i387_ext       
 st4          28   28    204      10 _i387_ext       
 st5          29   29    214      10 _i387_ext       
 st6          30   30    224      10 _i387_ext       
 st7          31   31    234      10 _i387_ext       
 fctrl        32   32    244       4 int             
 fstat        33   33    248       4 int             
 ftag         34   34    252       4 int             
 fiseg        35   35    256       4 int             
 fioff        36   36    260       4 int             
 foseg        37   37    264       4 int             
 fooff        38   38    268       4 int             
 fop          39   39    272       4 int             
 xmm0         40   40    276      16 vec128          
 xmm1         41   41    292      16 vec128          
 xmm2         42   42    308      16 vec128          
 xmm3         43   43    324      16 vec128          
 xmm4         44   44    340      16 vec128          
 xmm5         45   45    356      16 vec128          
 xmm6         46   46    372      16 vec128          
 xmm7         47   47    388      16 vec128          
 xmm8         48   48    404      16 vec128          
 xmm9         49   49    420      16 vec128          
 xmm10        50   50    436      16 vec128          
 xmm11        51   51    452      16 vec128          
 xmm12        52   52    468      16 vec128          
 xmm13        53   53    484      16 vec128          
 xmm14        54   54    500      16 vec128          
 xmm15        55   55    516      16 vec128          
 mxcsr        56   56    532       4 i386_mxcsr      
 ''           57   57    536       0 int0_t          
 ''           58   58    536       0 int0_t          
 ''           59   59    536       0 int0_t          
 ''           60   60    536       0 int0_t          
 ''           61   61    536       0 int0_t          
 ''           62   62    536       0 int0_t          
 ''           63   63    536       0 int0_t          
 ''           64   64    536       0 int0_t          
 ''           65   65    536       0 int0_t          
 ''           66   66    536       0 int0_t          
 ''           67   67    536       0 int0_t          
 ''           68   68    536       0 int0_t          
 ''           69   69    536       0 int0_t          
 ''           70   70    536       0 int0_t          
 ''           71   71    536       0 int0_t          
 ''           72   72    536       0 int0_t          
 ''           73   73    536       0 int0_t          
 ''           74   74    536       0 int0_t          
 ''           75   75    536       0 int0_t          
 ''           76   76    536       0 int0_t          
 ''           77   77    536       0 int0_t          
 ''           78   78    536       0 int0_t          
 ''           79   79    536       0 int0_t          
 ''           80   80    536       0 int0_t          
 ''           81   81    536       0 int0_t          
 ''           82   82    536       0 int0_t          
 ''           83   83    536       0 int0_t          
 ''           84   84    536       0 int0_t          
 ''           85   85    536       0 int0_t          
 ''           86   86    536       0 int0_t          
 ''           87   87    536       0 int0_t          
 ''           88   88    536       0 int0_t          
 ''           89   89    536       0 int0_t          
 ''           90   90    536       0 int0_t          
 ''           91   91    536       0 int0_t          
 ''           92   92    536       0 int0_t          
 ''           93   93    536       0 int0_t          
 ''           94   94    536       0 int0_t          
 ''           95   95    536       0 int0_t          
 ''           96   96    536       0 int0_t          
 ''           97   97    536       0 int0_t          
 ''           98   98    536       0 int0_t          
 ''           99   99    536       0 int0_t          
 ''          100  100    536       0 int0_t          
 ''          101  101    536       0 int0_t          
 ''          102  102    536       0 int0_t          
 ''          103  103    536       0 int0_t          
 ''          104  104    536       0 int0_t          
 ''          105  105    536       0 int0_t          
 ''          106  106    536       0 int0_t          
 ''          107  107    536       0 int0_t          
 ''          108  108    536       0 int0_t          
 ''          109  109    536       0 int0_t          
 ''          110  110    536       0 int0_t          
 ''          111  111    536       0 int0_t          
 ''          112  112    536       0 int0_t          
 ''          113  113    536       0 int0_t          
 ''          114  114    536       0 int0_t          
 ''          115  115    536       0 int0_t          
 ''          116  116    536       0 int0_t          
 ''          117  117    536       0 int0_t          
 ''          118  118    536       0 int0_t          
 ''          119  119    536       0 int0_t          
 ''          120  120    536       0 int0_t          
 ''          121  121    536       0 int0_t          
 ''          122  122    536       0 int0_t          
 ''          123  123    536       0 int0_t          
 ''          124  124    536       0 int0_t          
 ''          125  125    536       0 int0_t          
 ''          126  126    536       0 int0_t          
 ''          127  127    536       0 int0_t          
 ''          128  128    536       0 int0_t          
 ''          129  129    536       0 int0_t          
 ''          130  130    536       0 int0_t          
 ''          131  131    536       0 int0_t          
 ''          132  132    536       0 int0_t          
 ''          133  133    536       0 int0_t          
 ''          134  134    536       0 int0_t          
 ''          135  135    536       0 int0_t          
 ''          136  136    536       0 int0_t          
 ''          137  137    536       0 int0_t          
 ''          138  138    536       0 int0_t          
 ''          139  139    536       0 int0_t          
 ''          140  140    536       0 int0_t          
 ''          141  141    536       0 int0_t          
 ''          142  142    536       0 int0_t          
 ''          143  143    536       0 int0_t          
 ''          144  144    536       0 int0_t          
 ''          145  145    536       0 int0_t          
 ''          146  146    536       0 int0_t          
 ''          147  147    536       0 int0_t          
 ''          148  148    536       0 int0_t          
 ''          149  149    536       0 int0_t          
 ''          150  150    536       0 int0_t          
 orig_rax    151  151    536       8 long            
 al          152    0    544       1 int8_t          
 bl          153    1    545       1 int8_t          
 cl          154    2    546       1 int8_t          
 dl          155    3    547       1 int8_t          
 sil         156    4    548       1 int8_t          
 dil         157    5    549       1 int8_t          
 bpl         158    6    550       1 int8_t          
 spl         159    7    551       1 int8_t          
 r8l         160    8    552       1 int8_t          
 r9l         161    9    553       1 int8_t          
 r10l        162   10    554       1 int8_t          
 r11l        163   11    555       1 int8_t          
 r12l        164   12    556       1 int8_t          
 r13l        165   13    557       1 int8_t          
 r14l        166   14    558       1 int8_t          
 r15l        167   15    559       1 int8_t          
 ah          168   16    560       1 int8_t          
 bh          169   17    561       1 int8_t          
 ch          170   18    562       1 int8_t          
 dh          171   19    563       1 int8_t          
 ax          172   20    564       2 int16_t         
 bx          173   21    566       2 int16_t         
 cx          174   22    568       2 int16_t         
 dx          175   23    570       2 int16_t         
 si          176   24    572       2 int16_t         
 di          177   25    574       2 int16_t         
 bp          178   26    576       2 int16_t         
 ''          179   27    578       2 int16_t         
 r8w         180   28    580       2 int16_t         
 r9w         181   29    582       2 int16_t         
 r10w        182   30    584       2 int16_t         
 r11w        183   31    586       2 int16_t         
 r12w        184   32    588       2 int16_t         
 r13w        185   33    590       2 int16_t         
 r14w        186   34    592       2 int16_t         
 r15w        187   35    594       2 int16_t         
 eax         188   36    596       4 int32_t         
 ebx         189   37    600       4 int32_t         
 ecx         190   38    604       4 int32_t         
 edx         191   39    608       4 int32_t         
 esi         192   40    612       4 int32_t         
 edi         193   41    616       4 int32_t         
 ebp         194   42    620       4 int32_t         
 esp         195   43    624       4 int32_t         
 r8d         196   44    628       4 int32_t         
 r9d         197   45    632       4 int32_t         
 r10d        198   46    636       4 int32_t         
 r11d        199   47    640       4 int32_t         
 r12d        200   48    644       4 int32_t         
 r13d        201   49    648       4 int32_t         
 r14d        202   50    652       4 int32_t         
 r15d        203   51    656       4 int32_t         
*1: Register type's name NULL.
```

**Comment by itsbriany** [comment]
I ran r2, specifying the arch/os pair. It is good to know that I cannot load symbols from remote gdb. However, after every command, I still keep getting *r_debug_gdb_reg_read: small buffer 536 vs 544* after each command. Is this normal behaviour?

```bash
itsbriany@linux:~/Playground/infosec/c++$ r2 -a x86 -b 64 -D gdb gdb://localhost:1234                                                                                           [83/3927]
Debugging pid = 6, tid = 6 now
XWJSTEP TOFALSE
Attached debugger to pid = 36194800, tid = 1
Debugging pid = 36194800, tid = 1 now
r_debug_gdb_reg_read: small buffer 536 vs 544
r_debug_gdb_reg_read: small buffer 536 vs 544
 -- This is just an existentialist experiment.
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> aa
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> pd 20
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 80 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported
r_reg_get_value: Bit size 128 not supported

-----------------------------------------------------------
<more r_reg_get_values to show....>
-----------------------------------------------------------

           ;-- rip:
           0x7ffff7ddb2d0    4889e7         mov rdi, rsp
           0x7ffff7ddb2d3    e898370000     call 0x7ffff7ddea70        ;0x7ffff7ddea70() ; rip
           0x7ffff7ddb2d8    4989c4         mov r12, rax
           0x7ffff7ddb2db    8b05171b2200   mov eax, dword [rip + 0x221b17] ; [0x7ffff7ffcdf8:4]=0
           0x7ffff7ddb2e1    5a             pop rdx
           0x7ffff7ddb2e2    488d24c4       lea rsp, [rsp + rax*8]
           0x7ffff7ddb2e6    29c2           sub edx, eax
           0x7ffff7ddb2e8    52             push rdx
           0x7ffff7ddb2e9    4889d6         mov rsi, rdx
           0x7ffff7ddb2ec    4989e5         mov r13, rsp
           0x7ffff7ddb2ef    4883e4f0       and rsp, 0xfffffffffffffff0
           0x7ffff7ddb2f3    488b3d661d22.  mov rdi, qword [rip + 0x221d66] ; [0x7ffff7ffd060:8]=0
           0x7ffff7ddb2fa    498d4cd510     lea rcx, [r13 + rdx*8 + 0x10] ; 0x10 
           0x7ffff7ddb2ff    498d5508       lea rdx, [r13 + 8]         ; 0x8 
           0x7ffff7ddb303    31ed           xor ebp, ebp
           0x7ffff7ddb305    e8a6ee0000     call 0x7ffff7dea1b0        ;0x7ffff7dea1b0(unk) ; rip
           0x7ffff7ddb30a    488d154ff200.  lea rdx, [rip + 0xf24f]    ; 0x7ffff7dea560 
           0x7ffff7ddb311    4c89ec         mov rsp, r13
           0x7ffff7ddb314    41ffe4         jmp r12
           0x7ffff7ddb317    660f1f840000.  nop word [rax + rax]
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> db 0x7ffff7ddb2d8
Can't place a breakpoint here. No mapped memory
r_debug_gdb_reg_read: small buffer 536 vs 544
[0x7ffff7ddb2d0]> db
r_debug_gdb_reg_read: small buffer 536 vs 544
```

I also noticed r2 mentioning there is no mapped memory. I assume this is because r2 does not have the file loaded into its memory and is instead requesting gdb for the data?

**Comment by radare** [comment]
It means that the reg profile is wrong mainly because those 80 and 128 bit registers are not supported yet by rreg. Those definitions should be commented out from the profile and add an issue to implement it. Looks like gp regs and memory is read fine

**Comment by itsbriany** [comment]
Thanks radare & XVilka, hopefully 80 and 128 bit registers will be supported soon!
