### ISSUE TITLE
Ragg2 not working for ARM

### ISSUE THREAD

**Issue by jcorina** [radare/radare2#3215]
##### r_egg file 'hi.r':
write@syscall(4)

main@global(128) {
	.var1 = "sup";
	write(1, .var1, 3);
}

$ ragg2 -b 32 -a arm hi.r -F > ye

$ r2 -v
radare2 0.10.0-git 8568 @ linux-little-x86-64 git.0.9.9-469-gb2f0c86
commit: b2f0c86bb15fa410807d24d3b3e6ddb45d65d547 build: 2015-07-28

##### Arm box:
$ ./ye
Segmentation fault

$ uname -a
Linux (none) 3.11.4 #13 SMP Fri Jul 11 00:48:31 PDT 2014 armv7l GNU/Linux

**Comment by crowell** [comment]
this gets assembled to 

```
[0x00000000]> pd 20
           0x00000000    00482de9       push {fp, lr}
           0x00000004    04b08de2       add fp, sp, 4
           0x00000008    80d04de2       sub sp, sp, 0x80
           0x0000000c    fcf08fe2       add pc, pc, 0xfc               ; 272
           0x00000010    73757000       rsbseq r7, r0, r3, ror r5
           0x00000014    0c004fe2       sub r0, pc, 0xc
           0x00000018    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x0000001c    0300a0e3       mov r0, 3
           0x00000020    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x00000024    0100a0e3       mov r0, 1
           0x00000028    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x0000002c    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x00000030    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x00000034    ffffffe5       ldrb pc, [pc, 0xfff]!
           0x00000038    0400a0e3       mov r0, 4
           0x0000003c    008000ef       svc 0x8000                     ;syscall[0xffffffff][0]=?
           0x00000040    80d08be2       add sp, fp, 0x80
           0x00000044    0088bde8       pop {fp, pc}
```

which that instruction 

```
           0x0000000c    fcf08fe2       add pc, pc, 0xfc               ; 272
```
jumps outside of the code

**Comment by crowell** [comment]
https://asciinema.org/a/bjpnbwqrvdvy36lxo0ocmgf1q

wow esil is useful ;)

**Comment by crowell** [comment]
looks to be 2 bugs

1 - assembler gives add pc, $-4 to  add pc, 0xfc
and add pc $-4 is an infinite loop, no?

https://gist.github.com/7e3a1fdf619c03882d99

**Comment by radare** [comment]
@jcorina the output of your command is in hexpairs, not in binary,

@crowell https://github.com/radare/radare2/commit/c8cb347a4143cd189a27c3c484c5d45dc4f90be5 try again. nope is not an infinite loop, because this value is unsigned and the value of pc is the next one of the current, so it is `jmp $$ + 8 + ARG`

**Comment by radare** [comment]
```
$ ragg2 -r -b 32 -a arm hi.r > hi
$ r2 -a arm -b 32 hi
```

i have fixed some bugs in the arm assembler too. as well as other issues in the arm emitter of the egg module. but didnt tried the code. can you test now?

```
$ ragg2 -a arm -b 32 -s hi.r

.global main
main:
  push {fp,lr}
  add fp, sp, $4
  sub sp, 128
# encode filtered string (sup) ((null))
  add pc, 0
.string "sup"
  sub r0, pc, 16
  str r0, [sp, 8]
# rcc_fun 1 (write)
  mov r0, 3
  str r0, [sp, 12]
  mov r0, 1
  str r0, [sp, 20]
# set syscall args
  ldr r1, [sp, 8]
  ldr r2, [sp, 12]
  ldr r3, [sp, 20]
# syscall
 mov r0, 4
 svc 0x8000
  __end_0_1_1:
  add sp, fp, 128
  pop {fp,pc}
```

**Comment by jcorina** [comment]
Hm, so I thought the -F made it so it didn't output it in hexpairs:
 -F              output native format (osx=mach0, linux=elf, ..)

I'm still getting segfaults when I try with the command I had tried earlier:
ragg2 -b 32 -a arm hi.r -F > ye

Trying your method of outputting the asm and then compiling that I first get a complaint about:
mov r0, 4

because there's no '$' before the 4. When fixing that it compiles but when I try running it I get an illegal instr exception.

**Comment by crowell** [comment]
still broken 

https://asciinema.org/a/8zup335us9uch2nyo2ki6wq5i

**Comment by crowell** [comment]
hoho i see the problem. r0 is not the register that holds the first argument... should be r7 :-1: i'll fix this

**Comment by crowell** [comment]
and still more problems, so can't close yet, 

```
jeff@lostwoods ~ $ strace ./hi 
execve("./hi", ["./hi"], [/* 18 vars */]) = 0
write(1, "\0\360\217", 3)               = 1
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLTRP, si_addr=0x40088} ---
```

after i fix this, we need an arm test -__-

**Comment by crowell** [comment]
fixed now

```
minishwoods /tmp » cat hi.r 
write@syscall(4)
exit@syscall(1)

main@global(128) {
        .var1 = "sup";
        write(1, .var1, 3);
        exit(0);
}
```

```
jeff@lostwoods ~ $ ./hi 
sup
```

**Comment by radare** [comment]
Are you running latest r2 from git?
