### ISSUE TITLE
Cannot set hardware breakpoint on 64-bit linux when debugging a 32-bit program.

### ISSUE THREAD

**Issue by qdii** [radare/radare2#3935]
I was trying to set a hardware breakpoint: `drx 0 0x080480c1 4 rwx`
It returned:
> p/native/linux/linux_debug.c:428 ptrace: Invalid argument

I attached strace to radare2 to see what it was asking ptrace:

```
[~]$ sudo strace -p 3385               
Process 3385 attached
read(0, "\33", 1)                       = 1
write(1, "\33[0K\r", 5)                 = 5
read(0, "[", 1)                         = 1
read(0, "A", 1)                         = 1
write(1, "\r\33[2K\r\r\33[0m:> drx 0 0x080480c1 4"..., 66) = 66
read(0, "\303", 1)                      = 1
read(0, "\247", 1)                      = 1
write(1, "\33[0K\r", 5)                 = 5
write(1, "\r\33[2K\r\r\33[0m:> drx 0 0x080480c1 4"..., 70) = 70
read(0, "\177", 1)                      = 1
write(1, "\33[0K\r", 5)                 = 5
write(1, "\r\33[2K\r\r\33[0m:> drx 0 0x080480c1 4"..., 66) = 66
read(0, "\r", 1)                        = 1
write(1, "\33[0K\r", 5)                 = 5
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or SNDRV_TIMER_IOCTL_TREAD or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\r\33[2K\r", 6)               = 6
write(1, "\r\33[0m:> drx 0 0x080480c1 4 rwx\n", 31) = 31
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg), [0x80480c1]) = 0
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg) + 8, [0]) = 0
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg) + 16, [0]) = 0
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg) + 24, [0]) = 0
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg) + 48, [0]) = 0
ptrace(PTRACE_PEEKUSER, 7487, offsetof(struct user, u_debugreg) + 56, [0]) = 0
ptrace(PTRACE_POKEUSER, 7487, offsetof(struct user, u_debugreg), 0x80480c1) = 0
ptrace(PTRACE_POKEUSER, 7487, offsetof(struct user, u_debugreg) + 8, 0) = 0
ptrace(PTRACE_POKEUSER, 7487, offsetof(struct user, u_debugreg) + 16, 0) = 0
ptrace(PTRACE_POKEUSER, 7487, offsetof(struct user, u_debugreg) + 24, 0xc000100000000) = -1 EINVAL (Invalid argument)
write(2, "ptrace error for dr 3\n", 22) = 22
write(2, "p/native/linux/linux_debug.c:428"..., 58) = 58
```

**Comment by skuater** [comment]
fixed, but plz take in mind use the correct hw bp type:
w = break when data write
r = break when data read or write
x = break on execution
u cant assign "rx" or "wx" or "rwx", if u want do a "rwx" u need use 2 hw bp:
drx 0 entry0 r  <--- set bp on read and write 
drx 1 entry0 x <--- set bp on execution

**Comment by qdii** [comment]
Noted :) thanks for the quick fix

**Comment by Vafa-Andalibi** [comment]
I still have this problem on Kali 2019 using the following version of radare2: 
```
r2: invalid option -- '-'
radare2 3.2.1 0 @ linux-x86-64 git.
commit: unknown build: 2019-03-02__19:36:59
```
output: 
```
[0x08048060]> px 4 @ 0xff9a03d8
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0xff9a03d8  4141 4141                                AAAA
[0x08048060]> drx 0 0xff9a03d8 4 r
ptrace error for dr 3
ptrace POKEUSER: Invalid argument
[0x08048060]> drx 0 0xff9a03d8 1 r
ptrace error for dr 3
ptrace POKEUSER: Invalid argument
[0x08048060]> 
```


strace log on the last command `drx 0 0xff9a03d8 1 r`: 

```
# strace -p 2013
strace: Process 2013 attached
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigreturn({mask=[]})                 = -1 EINTR (Interrupted system call)
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "\33", 1)                       = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[2K\r", 5)                 = 5
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
write(1, "\r\33[2K\r", 6)               = 6
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "[", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "A", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\r\33[0m\33[38;2;255;255;0m[0x0804806"..., 116) = 116
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "\33", 1)                       = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[2K\r", 5)                 = 5
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
write(1, "\r\33[2K\r", 6)               = 6
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "[", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "A", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\r\33[0m\33[38;2;255;255;0m[0x0804806"..., 116) = 116
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "\33", 1)                       = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[2K\r", 5)                 = 5
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
write(1, "\r\33[2K\r", 6)               = 6
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "[", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "B", 1)                         = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\r\33[0m\33[38;2;255;255;0m[0x0804806"..., 116) = 116
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}) = 1 (in [0])
read(0, "\r", 1)                        = 1
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
write(1, "\33[2K\r", 5)                 = 5
write(1, "\r\33[2K\r\r\33[38;2;255;255;0m[0x08048"..., 63) = 63
kill(2015, 0)                           = 0
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
kill(2015, 0)                           = 0
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
write(2, "ptrace error for dr 3\n", 22) = 22
write(2, "ptrace POKEUSER: Invalid argumen"..., 34) = 34
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
write(1, "", 0)                         = 0
kill(2015, 0)                           = 0
futex(0x5654fa30b608, FUTEX_WAKE_PRIVATE, 1) = 1
rt_sigaction(SIGINT, {sa_handler=0x7f029fd07210, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f029f402100}, {sa_handler=0x7f029fd07210, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f029f402100}, 8) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=53, ws_col=206, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, TIOCGWINSZ, {ws_row=53, ws_col=206, ws_xpixel=0, ws_ypixel=0}) = 0
ioctl(0, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(0, SNDCTL_TMR_START or TCSETS, {B38400 opost -isig -icanon -echo ...}) = 0
ioctl(0, TCGETS, {B38400 opost -isig -icanon -echo ...}) = 0
write(1, "\33[2K\r", 5)                 = 5
write(1, "\33[0m\33[38;2;255;255;0m[0x08048060"..., 39) = 39
rt_sigaction(SIGINT, {sa_handler=0x7f029fd07210, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f029f402100}, {sa_handler=0x7f029fd07210, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f029f402100}, 8) = 0
rt_sigprocmask(SIG_BLOCK, [WINCH], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
pselect6(1, [0], NULL, NULL, NULL, {[], 8}

```

**Comment by GustavoLCR** [comment]
@Vafa-Andalibi Your radare2 is too old. Install it from git and try again. If it is still not working, open a new issue

**Comment by Vafa-Andalibi** [comment]
Updated the radare to 
```
r2: invalid option -- '-'
radare2 4.0.0-git 23025 @ linux-x86-64 git.3.9.0-187-g9ed199d64
commit: 9ed199d64e26f4df2d875fa63928089eb9d7c023 build: 2019-10-11__17:24:08
``` 
Still the same error. New issue opened (#15255)
