### ISSUE TITLE
regression in main vs sym..text

### ISSUE THREAD

**Issue by crowell** [radare/radare2#3993]
```
[0x00404870]> pdf@entry0
╒ (fcn) entry0 42
│           0x00404870      31ed           xor ebp, ebp
│           0x00404872      4989d1         mov r9, rdx
│           0x00404875      5e             pop rsi
│           0x00404876      4889e2         mov rdx, rsp
│           0x00404879      4883e4f0       and rsp, 0xfffffffffffffff0
│           0x0040487d      50             push rax
│           0x0040487e      54             push rsp
│           0x0040487f      49c7c0902441.  mov r8, 0x412490
│           0x00404886      48c7c1202441.  mov rcx, 0x412420           ; "AWAVA..AUATL.%.. " 0x00412420 
│           0x0040488d      48c7c7a02840.  mov rdi, section..text      ; "AWAVAUATUS..H..H...." @ 0x4028a0
│           0x00404894      e857dcffff     call sym.imp.__libc_start_main
╘           0x00404899      f4             hlt
```

this used to have ` mov rdi, main `

now it says ` mov rdi, section..text `

**Comment by Maijin** [comment]
Is it regression ? Because, this https://github.com/radare/radare2/issues/2876 has never been fixed

**Comment by Maijin** [comment]
Status?

**Comment by radare** [comment]
still not perfect

**Comment by Maijin** [comment]
we need binaries/test in r2r for that purpose

**Comment by radare** [comment]
i wrote a test for this by loading osx's /bin/ls and analyzing the entrypoint

<img width="622" alt="screen shot 2016-03-13 at 03 39 39" src="https://cloud.githubusercontent.com/assets/917142/13726565/42e16736-e8cd-11e5-90b6-e0aed91fff57.png">

**Comment by radare** [comment]
One solution would be to hardcode some rules like "main" > "entry*" > "sym.*"

**Comment by radare** [comment]
any interesting tests to look at @Maijin ?

**Comment by Maijin** [comment]
@crowell can you share the binary ?

**Comment by Maijin** [comment]
I'll add a test in r2r tomorrow based on #2876 bin

**Comment by Maijin** [comment]
so #2876 is fixed, what about your binary @crowell ?

**Comment by radare** [comment]
the root problem is not fixed, but if its ok for 99% of cases i would move this issue for 0.10.3

**Comment by radare** [comment]
the other day i found a binary that was failing a lot because of this issue.. if we cross our lives again i'll push it into r2r and write some tests

**Comment by ret2libc** [comment]
Can we have a binary to test this?

**Comment by radare** [comment]
i surely will upload if i find it again :P

**Comment by ret2libc** [comment]
@crowell what about this? is it fixed?

**Comment by radare** [comment]
no, it is not fixed, but i have no test for this.

**Comment by Maijin** [comment]
Let's close it until find another bin with this issue

**Comment by radare** [comment]
dont close it. move it to 0.10.4

**Comment by Maijin** [comment]
pff, useless, let's wait for another problem.

**Comment by radare** [comment]
????? I already said several times that inhave bins that reproduce this issue. Theres no code at all to handle tjis and we all know that it can be tricked to mess the disasm. So the bug is not gone

**Comment by radare** [comment]
Ill have time after release to care about this

**Comment by Maijin** [comment]
"no, it is not fixed, but i have no test for this."
"the other day i found a binary that was failing a lot because of this issue.. if we cross our lives again i'll push it into r2r and write some tests"

For me it's like u don't have it anymore :P

**Comment by radare** [comment]
i will have time to prepare some tests when i go back to carve the directory with the bins i was playing the other day.

i have also a bunch of other stuff i have been doing by hand in the queue to fill issues, send bugfixes and add tests. but this is not a reason for asuming this is ok
