### ISSUE TITLE
bad disassembly arm

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#4132]
I've seen this issue while disassembly ls from iOS 

https://asciinema.org/a/3bfa8v6oq6yxuv4aadj69je34

i think @ret2libc was working on this

![ls](https://cloud.githubusercontent.com/assets/3474042/13197789/3edd70ac-d7f8-11e5-8882-23444cdc57d1.png)

**Comment by radare** [comment]
e asm.bits=16

This thing was fixed for android because the thumb bit is set in rbin. It works for me on ios app binaries.

**Comment by alvarofe** [comment]
that doesn't resolve the issue i think.

at entry0 the bytes are `00009de40410..`, when moving with `j/k` in visual mode they become `00d111e3..` so something strange is happening there, although dumping the content is right. Maybe a regression?

<img width="1440" alt="captura de pantalla 2016-02-20 a las 19 17 30" src="https://cloud.githubusercontent.com/assets/3474042/13198342/9ff8ea70-d806-11e5-821e-b7b141c17b7e.png">

**Comment by radare** [comment]
Oh then it should be related to the ret2libc changes

**Comment by radare** [comment]
should be fixed now, it was a bug in r_io, please confirm and close

**Comment by alvarofe** [comment]
fixed
