### ISSUE TITLE
Rabin 2 is not happy :)..

### ISSUE THREAD

**Issue by Th4nat0s** [radare/radare2#4210]
When analysing a vb pe32 with rabin2 -I 

I got : 
```
Invalid version for module /usr/lib/radare2/0.10.2-git/asm_propeller.so
```
and several times
```
Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/MSVBVM60.sdb
``` 

A fresh installed radare with install.sh :)... 

I do confirm MSVBVM60.sdb is missing in my folder

**Comment by Th4nat0s** [comment]
Only a few comparing to : 
https://github.com/radare/radare2/tree/master/libr/bin/d/dll

```
$ll
total 64
-rw-r--r-- 1 root root  7872 Oct 23 16:17 CSMFPAPI.sdb
-rw-r--r-- 1 root root 15395 Oct 23 16:17 MSI.sdb
-rw-r--r-- 1 root root 17373 Oct 23 16:17 OLEAUT32.sdb
-rw-r--r-- 1 root root  8818 Oct 23 16:17 WS2_32.sdb
-rw-r--r-- 1 root root  4812 Oct 23 16:17 WSOCK32.sdb

```

**Comment by Th4nat0s** [comment]
Someting is broken in the install script i guess, if i do the step manually, is works

```
[09:51]:[~/code/radare2/libr/bin/d]\:: [master:87b6ada9
$make clean
rm -f dll/*.sdb
[09:51]:[~/code/radare2/libr/bin/d]\:: [master:87b6ada9
$make all
../../..//libr/../shlr/sdb//sdb dll/ws2_32.sdb = < dll/ws2_32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/oleaut32.sdb = < dll/oleaut32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/wsock32.sdb = < dll/wsock32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/msi.sdb = < dll/msi.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/csmfpapi.sdb = < dll/csmfpapi.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/msvbvm60.sdb = < dll/msvbvm60.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/kernel32.sdb = < dll/kernel32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/aclui.sdb = < dll/aclui.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/activeds.sdb = < dll/activeds.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/atl.sdb = < dll/atl.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/borlndmm.sdb = < dll/borlndmm.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/browseui.sdb = < dll/browseui.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/comctl32.sdb = < dll/comctl32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/dsound.sdb = < dll/dsound.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/mfc42.sdb = < dll/mfc42.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/mfc42u.sdb = < dll/mfc42u.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/mstlsapi.sdb = < dll/mstlsapi.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/msvbvm50.sdb = < dll/msvbvm50.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/odbc32.sdb = < dll/odbc32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/olecli32.sdb = < dll/olecli32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/oledlg.sdb = < dll/oledlg.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/olepro32.sdb = < dll/olepro32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/olesvr32.sdb = < dll/olesvr32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/shdocvw.sdb = < dll/shdocvw.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/shell32.sdb = < dll/shell32.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/shlwapi.sdb = < dll/shlwapi.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/uxtheme.sdb = < dll/uxtheme.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/vb40032.sdb = < dll/vb40032.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/vssapi.sdb = < dll/vssapi.sdb.txt
../../..//libr/../shlr/sdb//sdb dll/winmm.sdb = < dll/winmm.sdb.txt
[09:51]:[~/code/radare2/libr/bin/d]\:: [master:87b6ada9
$sudo make install
[i] Installing bin format files
rm -rf "/usr/share/radare2/0.10.2-git/format"
mkdir -p "/usr/share/radare2/0.10.2-git/format"
cp -f * "/usr/share/radare2/0.10.2-git/format" || true
cp: omitting directory ‘dll’
mkdir -p "/usr/share/radare2/0.10.2-git/format/dll"
cp -f dll/*.sdb "/usr/share/radare2/0.10.2-git/format/dll"
[09:51]:[~/code/radare2/libr/bin/d]\:: [master:87b6ada9
$ls "/usr/share/radare2/0.10.2-git/format/dll"
aclui.sdb     browseui.sdb  kernel32.sdb  mstlsapi.sdb  oleaut32.sdb  olesvr32.sdb  uxtheme.sdb  ws2_32.sdb
activeds.sdb  comctl32.sdb  mfc42.sdb     msvbvm50.sdb  olecli32.sdb  shdocvw.sdb   vb40032.sdb  wsock32.sdb
atl.sdb       csmfpapi.sdb  mfc42u.sdb    msvbvm60.sdb  oledlg.sdb    shell32.sdb   vssapi.sdb
borlndmm.sdb  dsound.sdb    msi.sdb       odbc32.sdb    olepro32.sdb  shlwapi.sdb   winmm.sdb
```

**Comment by Th4nat0s** [comment]
Oki understood... install put in in 

/usr/share/radare2/0.10.2-git/format/dll  and my rabin seek it in /usr/local/share/radare2/0.10.0-git/format/dll/

If i copy it manually **and change the name to UPPERCASE**.. is works !.. :)

**Comment by radare** [comment]
Those sdb files should be case insenstive.. The libname referenced in the executable is lowercased and checked in that directory.

**Comment by Th4nat0s** [comment]
If the uppercase file is not theyre.. I do confirm radare output a bunch of 

```Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/MSVBVM60.sdb```

**Comment by radare** [comment]
w t f i though that thing was there, anyway, i just pushed a fix for that, but i remember the commit was already there :???

**Comment by radare** [comment]
Should be fixed now. i found the missing commit it was incomplete patch.

**Comment by Th4nat0s** [comment]
Sorry but no, it is not fixed for me... using commit 3624931cdec3aaf1f301dccb753bd044a66f89b5

Then sudo rm /usr/local/share/radare2/0.10.0-git/format/dll/* then the install .sh script again...

I still have the "Cannot find /usr/local/share/radare2/0.10.0-git/format/dll/MSVBVM60.sdb" because the sdb files are generated in /usr/share/radare2/0.10.2-git/format/dll
When i copy the file.. and upercase IT.. (still required) .. It works.. but i still have the error

"Invalid version for module /usr/lib/radare2/0.10.2-git/asm_propeller.so"

Than'ks in advance.

**Comment by radare** [comment]
this is because you have to remove the plugins from older versions. are you compiling with sys/install? makr purge will remove old stuff from preiovus r2 installations.

all those files shuold be in lowercase. if you have it in uppercase, maybe a git clean -xdf will help in removing all the old files

**Comment by Th4nat0s** [comment]
did..
```
git clean -xdf
sudo make purge
./sys/install.sh
```

And all is working fine again.. Thank's for support.

**Comment by radare** [comment]
cool! :)
