### ISSUE TITLE
pf: print array of a user-defined format

### ISSUE THREAD

**Issue by ret2libc** [radare/radare2#4763]
If I do:
```
$ r2 -nn ./r2r/bins/elf/main
> pf elf_phdr @ elf_phdr
              type : 0x00000000 =  type (enum) = (null)
             flags : 0x00000004 =  flags (enum) = (null)
            offset : 0x00000008 = (qword) 0x0000000000000000
             vaddr : 0x00000010 = (qword) 0x00000001003e0002
             paddr : 0x00000018 = (qword) 0x0000000000400410
            filesz : 0x00000020 = (qword) 0x0000000000000040
             memsz : 0x00000028 = (qword) 0x0000000000000fc8
             align : 0x00000030 = (qword) 0x0038004000000000
```
I get the expected output, but if I do:
```
> pf {4}elf_phdr @ elf_phdr
0x00000040 = 100663296.000000
0x00000044 = (qword) 0x0500000040000000
0x0000004c = 0
Register (null) does not exists

0x00000050 = 4194368.000000
0x00000054 = (qword) 0x0040004000000000
0x0000005c = 0
Register (null) does not exists

0x00000060 = 3221291008.000000
0x00000064 = (qword) 0x00000000c0010000
0x0000006c = 0
Register (null) does not exists

0x00000070 = 8.000000
0x00000074 = (qword) 0x0000000300000000
0x0000007c = 4
Register (null) does not exists
```

I don't. Am I using pf in the wrong way or is it just a bug?

**Comment by Maijin** [comment]
@Hyask See this

**Comment by ret2libc** [comment]
Any news on this? @Maijin @Hyask

**Comment by Hyask** [comment]
I have currently no time at all for r2 with my studies, so I sadly think this will have to wait for this summer... :/
Sorry

**Comment by Hyask** [comment]
Just to see, I tried what you did, and I got the result you expect, so it works for me...

(Ubuntu 16.04, r2 commit: d651283c5745e7feefe37d6925ab9ff07d4ab42f)

**Comment by ret2libc** [comment]
@Hyask what I wrote in the first post was the wrong output. What I would expect is something like:
```
              type : 0x00000000 =  type (enum) = (null)
             flags : 0x00000004 =  flags (enum) = (null)
            offset : 0x00000008 = (qword) 0x0000000000000000
             vaddr : 0x00000010 = (qword) 0x00000001003e0002
             paddr : 0x00000018 = (qword) 0x0000000000400410
            filesz : 0x00000020 = (qword) 0x0000000000000040
             memsz : 0x00000028 = (qword) 0x0000000000000fc8
             align : 0x00000030 = (qword) 0x0038004000000000

              type : 0x00000038 =  type (enum) = (null)
             flags : 0x0000003c =  flags (enum) = (null)
            offset : 0x00000040 = (qword) 0x0000000000000000
             vaddr : 0x00000048 = (qword) 0x00000001003e0002
             paddr : 0x00000050 = (qword) 0x0000000000400410
            filesz : 0x00000058 = (qword) 0x0000000000000040
             memsz : 0x00000060 = (qword) 0x0000000000000fc8
             align : 0x00000068 = (qword) 0x0038004000000000
...
```

**Comment by Hyask** [comment]
okay, sorry for not reading enough carefully

Anyway, before a fix comes, you can always do that `pf [4]? (elf_phdr)a_random_name @ elf_phdr`

**Comment by ret2libc** [comment]
Uh that's exactly what I would like to have! Cool, thanks a lot.

**Comment by Hyask** [comment]
Have fun! :)

**Comment by ret2libc** [comment]
Test added in 23456431259b71a865c7e4c221f7361b76b822b8

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/commit/23456431259b71a865c7e4c221f7361b76b822b8

**Comment by Maijin** [comment]
Fixed

**Comment by ret2libc** [comment]
where? both the test cases in r2r and the test case I wrote in the main msg of this issue seem still wrong to me :(

**Comment by Maijin** [comment]
The test you added is broken= ? So it means it passes that's why i closed it

**Comment by Maijin** [comment]
https://github.com/radare/radare2-regressions/blob/master/t/cmd_pf#L515
