### ISSUE TITLE
dmi giving incorrect values

### ISSUE THREAD

**Issue by Owlz** [radare/radare2#5345]
It appears that dmi is giving incorrect values for symbol lookups in loaded modules. In my case, I load up an application, it loads the module, i break, then check for the location of a symbol in one of the modules.

```
[0x7f7f0c803110]> dmm
0x00400000 /home/home/opt/pyThaw/tmp/build/exe.linux-x86_64-3.5/example1_freeze
0x7f7f0ab0d000 /usr/lib/locale/locale-archive
0x7f7f0b4cc000 /lib/x86_64-linux-gnu/libm-2.23.so
0x7f7f0b7d5000 /lib/x86_64-linux-gnu/libutil-2.23.so
0x7f7f0b9d8000 /lib/x86_64-linux-gnu/libdl-2.23.so
0x7f7f0bbdc000 /lib/x86_64-linux-gnu/libz.so.1.2.8
0x7f7f0bdf6000 /lib/x86_64-linux-gnu/libexpat.so.1.6.0
0x7f7f0c01f000 /lib/x86_64-linux-gnu/libc-2.23.so
0x7f7f0c3e8000 /lib/x86_64-linux-gnu/libpthread-2.23.so
0x7f7f0c605000 /home/home/opt/pyThaw/tmp/build/exe.linux-x86_64-3.5/libpython3.5m.so.1.0
0x7f7f0cc8c000 /lib/x86_64-linux-gnu/ld-2.23.so
0x7f7f0cea8000 /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
0x7f7f0ceb1000 /lib/x86_64-linux-gnu/ld-2.23.so
```

That base is correct, however:

```
[0x7f7f0c803110]> dmi libpython3.5m.so.1.0 PyImport_FrozenModules
vaddr=0x00a4d5c8 paddr=0x0044d5c8 ord=633 fwd=NONE sz=8 bind=GLOBAL type=OBJECT name=PyImport_FrozenModules
```

Those addresses of the symbols appear to be incorrect. Specifically, vaddr is always off by 0x200000. However, if i load up the module directly in r2, and utilize is:

```
[0x00062ff0]> is~PyImport_FrozenModules
vaddr=0x0064d5c8 paddr=0x0044d5c8 ord=633 fwd=NONE sz=8 bind=GLOBAL type=OBJECT name=PyImport_FrozenModules
```

That vaddr is the correct offset. I'm unsure if the vaddr being off by 0x200000 is intentional or not for dmi. Seems confusing though.

**Comment by radare** [comment]
This delta is the baddr which can be wrongly computed. Can you verify this? Is this lib aslrd and loaded at different places and always shifted by this offset?

**Comment by Owlz** [comment]
Interestingly, I actually had deleted that exact one. I re-built a similar
one. Re-loaded it a few time to test the offsets. This time, every time it
reloaded it was off by 0x400000. The base was indeed changing on load and
it was constantly off by this amount. The library itself is compiled
position independent code.

**Comment by radare** [comment]
Aaah i think thats because its using the base address of the esecutable instead of the one from the library. This looks like a regression because al that stuff worked when i implemented it. Will give a try when i got a chance to touch a keyboard again

**Comment by radare** [comment]
works for me in osx.can u verify again?

**Comment by dequis** [comment]
This is labeled as regression, but regression from what point?

Anyway, Linux x86_64, I guess it still happens (also reproduced [these bins](https://github.com/Owlz/pyThaw/tree/master/examples/example1_freeze), but going with /bin/ls for simplicity)

```
$ r2 -d /bin/ls
Process with PID 31538 started...
= attach 31538 31538
bin.baddr 0x00400000
Assuming filepath /bin/ls
asm.bits 64
 -- Puritans, ruining everything since the 16th century.
[0x7fdbb4f3ad70]> db main
[0x7fdbb4f3ad70]> dc
[...]
[0x00402a00]> dmm
0x00400000 /usr/bin/ls
0x7fdbb4998000 /usr/lib/libc-2.24.so
0x7fdbb4d36000 /usr/lib/libcap.so.2.25
0x7fdbb4f3a000 /usr/lib/ld-2.24.so
[0x00402a00]> dmi ~cap
vaddr=0x00402330 paddr=0x00002330 ord=004 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.cap_to_text
vaddr=0x004028c0 paddr=0x000028c0 ord=092 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.cap_get_file
vaddr=0x004028e0 paddr=0x000028e0 ord=095 fwd=NONE sz=16 bind=GLOBAL type=FUNC name=imp.cap_free
```

If I'm interpreting this right instead of vaddr=0x00402330 it should be 0x2330 + 0x7fdbb4d36000 = 0x7fdbb4d38330. Is that how it works in osx too?

```
$ r2 /usr/lib/libcap.so.2.25
 -- I love gradients.
[0x00001560]> is ~cap_to_text,cap_get_file,cap_free
vaddr=0x00002570 paddr=0x00002570 ord=040 fwd=NONE sz=1083 bind=GLOBAL type=FUNC name=cap_to_text
vaddr=0x000016d0 paddr=0x000016d0 ord=045 fwd=NONE sz=148 bind=GLOBAL type=FUNC name=cap_free
vaddr=0x00002bb0 paddr=0x00002bb0 ord=051 fwd=NONE sz=108 bind=GLOBAL type=FUNC name=cap_get_file
```

I'm slightly concerned about paddr not matching.

**Comment by radare** [comment]
Nope the import is in the executable memory space, this is fine. But you want the symbol from thw lib which needs loading rhe symbols from that lib. And you only have the symbols of the bin right now

**Comment by dequis** [comment]
Oh, right, imports. Should have just used the binaries from OP instead, that's much clearer.

radare2 0.10.6-357-gbdcd1df

```
[0x00403dd0]> dm~libpy
sys 2.2M 0x00007fda47e85000 - 0x00007fda480bb000 s -r-x /usr/lib/libpython3.5m.so.1.0 /usr/lib/libpython3.5m.so.1.0
sys   2M 0x00007fda480bb000 - 0x00007fda482bb000 s ---- /usr/lib/libpython3.5m.so.1.0 /usr/lib/libpython3.5m.so.1.0
sys   8K 0x00007fda482bb000 - 0x00007fda482bd000 s -r-- /usr/lib/libpython3.5m.so.1.0 /usr/lib/libpython3.5m.so.1.0
sys 404K 0x00007fda482bd000 - 0x00007fda48322000 s -rw- /usr/lib/libpython3.5m.so.1.0 /usr/lib/libpython3.5m.so.1.0
[0x00403dd0]> dmi libpython3.5m.so.1.0 PyImport_FrozenModules
vaddr=0x0089cd28 paddr=0x0029cd28 ord=486 fwd=NONE sz=8 bind=GLOBAL type=OBJECT name=PyImport_FrozenModules
```


radare2 0.9.7 (picked some arbitrarily old release)

```
[0x00403dd1]> dm~libpy
sys 0x7fa95bea2000 - 0x7fa95c0d8000 s r-x /usr/lib/libpython3.5m.so.1.0
sys 0x7fa95c0d8000 - 0x7fa95c2d8000 s --- /usr/lib/libpython3.5m.so.1.0
sys 0x7fa95c2d8000 - 0x7fa95c2da000 s r-- /usr/lib/libpython3.5m.so.1.0
sys 0x7fa95c2da000 - 0x7fa95c33f000 s rw- /usr/lib/libpython3.5m.so.1.0
[0x00403dd1]> dmi libpython3.5m.so.1.0 PyImport_FrozenModules
[Symbols]
addr=0x005d0490 off=0x005d0490 ord=341 fwd=NONE sz=8 bind=GLOBAL type=OBJECT name=PyImport_FrozenModules

1 symbols
```

radare2 0.9.6

```
[0x00403dd0]> dm~libpy
sys 0x7fb3de249000 - 0x7fb3de47f000 s r-x /usr/lib/libpython3.5m.so.1.0
sys 0x7fb3de47f000 - 0x7fb3de67f000 s --- /usr/lib/libpython3.5m.so.1.0
sys 0x7fb3de67f000 - 0x7fb3de681000 s r-- /usr/lib/libpython3.5m.so.1.0
sys 0x7fb3de681000 - 0x7fb3de6e6000 s rw- /usr/lib/libpython3.5m.so.1.0
[0x00403dd0]> dmi libpython3.5m.so.1.0 PyImport_FrozenModules
[Symbols]
addr=0x7fb3de819490 off=0x005d0490 ord=341 fwd=NONE sz=8 bind=GLOBAL type=OBJECT name=PyImport_FrozenModules

1 symbols
```

0x7fb3de819490 - 0x7fb3de249000 = 0x5d0490

So radare2 0.9.6 does it right, 0.9.7 doesn't add any base address at all, and current git adds the wrong base address (from the executable instead of the library). Sounds good?

**Comment by radare** [comment]
Indeed. Thats a regression

**Comment by dequis** [comment]
Okay, bisect points at 1c4756898e5234bd58e2ab99d43db74845420ebf, "Updated the r_core_bin_info function and changed some "offset" arguments to baseaddr"

```diff
diff --git a/libr/core/file.c b/libr/core/file.c
index 2c8456a..a0e2a20 100644
--- a/libr/core/file.c
+++ b/libr/core/file.c
@@ -281,10 +281,9 @@ R_API int r_core_bin_load(RCore *r, const char *file, ut64 baddr) {

        r_config_set_i (r->config, "io.va",
                (r->bin->cur->o->info)? r->bin->cur->o->info->has_va: 0);
-       // XXX - this needs to be fixed (offset is ignored), r_core_bin_info gets
-       // the base address information directly from the binary now.
        offset = r_bin_get_offset (r->bin);
-       r_core_bin_info (r, R_CORE_BIN_ACC_ALL, R_CORE_BIN_SET, va, NULL, offset);
+       // XXX - should this be offset, base address, or base address + offset. (referring to the last argument)
+       r_core_bin_info (r, R_CORE_BIN_ACC_ALL, R_CORE_BIN_SET, va, NULL, r_bin_get_baddr(r->bin));

        if (r->bin->cur->curplugin && !strcmp (r->bin->cur->curplugin->name, "dex")) {
                r_core_cmd0 (r, "\"(fix-dex,wx `#sha1 $s-32 @32` @12 ; wx `#adler32 $s-12 @12` @8)\"\n");
```

Sounds like it was changed without being sure what the right way is, and it only extended the XXX comment to add more doubts. Also I think offset isn't ignored like the old version of the XXX said.

May be worth noting that the commits around that one (ae2f696...1053453) had a bug in r_debug_reg_sync() that displayed the instruction pointer (and all registers) as 0 but, other than that, it worked well enough to bisect it properly.

**Comment by alvarofe** [comment]
should be fixed now test please again and close it when confirmed

**Comment by radare** [comment]
confirmed
