### ISSUE TITLE
Getting int3 while debugging

### ISSUE THREAD

**Issue by sferrini** [radare/radare2#6223]
While debugging a binary, radare2 sometime adds a strange `int3` to the disassembly (even if the binary doesn't actually contains it). And if I try to step again I get the `child stopped with signal 11` error.

As example I tried with this public available binary: https://github.com/RPISEC/MBE/blob/master/src/lab01/lab1A
This is the asciinema:
https://asciinema.org/a/23ta599al39u51fhnt2xjpjgs

I have the same problem also with other binaries, this is another example:
https://asciinema.org/a/9fsjmg5lxan0ci1tze2q76149

**Comment by radare** [comment]
can you try again? we have fixed a bunch of bugs in the debugger today

**Comment by sferrini** [comment]
@radare yes sure, just tried with the same binary: https://asciinema.org/a/98nsael7no94le996jrhzfe8q and also with another one: https://asciinema.org/a/1u0xpi2wle0qw6c4m2b35iqa8 seems that now the execution stops at the first instruction.

**Comment by sferrini** [comment]
Also seems that I still have this issue https://github.com/radare/radare2/issues/6218 even with the latest commit.

**Comment by radare** [comment]
what are you exactly doing? i dont see which keys are you pressing. is this a step, step over? are you using swstep? i assume tihs happens when you are stepping over a breakpoint on a specific kind of instruction? im trying hard but dont manage to reproduce it at all.. i just see that if i step over a breakpoint, the breakpoint is removed

**Comment by radare** [comment]
which kernel are you using? is this on x86-32 on x86-64 or all 32bits? also i'm assuming you are using r2 from git and i also assume you dont have any custom config in your radare2rc, right?

can you paste a script to reproduce this bug? it is important if we want to include it in the regressions testsuite..

**Comment by radare** [comment]
it is also happening with 64bit binaries?

**Comment by sferrini** [comment]
I'm using an ubuntu xenial64 VM with vagrant from a 64 bit machine:

```
$ uname -a
Linux ubuntu-xenial 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Yes I'm using r2 from git at the latest commit. And I don't have any custom config in radare2rc.

Just tried with `/bin/ls` (is 64 bit) and seems fine (the execution doesn't stops).

**Comment by sferrini** [comment]
To answer the question about the keys pressed, in this asciinema https://asciinema.org/a/98nsael7no94le996jrhzfe8q I don't press any key in visual mode. I go there just to show that in the disassembly before doing a step over (`dso`) there is no `int3`, and after the step it appears.

**Comment by radare** [comment]
ok i was able to reproduce it. looks like if you set `e asm.bits=64` right after the `r2 -d lab01` everything works fine (except the registers are names rax instead of eax and so on..) so it's a problem related to the x86-64-to-32 register profile. afaik we just fixed native 64 and native 32 bit regprofiles yesterday. lemme re-chk

**Comment by sferrini** [comment]
Sure thanks!

Anyway this is the script:
```python
import r2pipe

r2 = r2pipe.open("lab1A")
print(r2.cmd("aaa"))
print(r2.cmd("ood"))
print(r2.cmd("db main"))
print(r2.cmd("dc"))
print(r2.cmd("dso"))
```

Use it with this binary: https://github.com/RPISEC/MBE/blob/master/src/lab01/lab1A

And the output is:

```

Process with PID 2882 started...
File dbg:///vagrant_data/src_mbe/format-strings/lab1A  reopened in read-only mode
= attach 2882 2882
Assuming filepath /vagrant_data/src_mbe/format-strings/lab1A


r_debug_reg: error writing registers 0 to 2882
cannot set registers!
= attach 2882 1

child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0x0000005d code=1 ret=0
```

**Comment by radare** [comment]
you dont need r2pipe to make a script that does that. just r2 -i scriptfile and put the commands in `scriptfile`

**Comment by radare** [comment]
also i dont think the analysis affects at all

**Comment by sferrini** [comment]
Oh cool, I thought the analysis was needed to use the `main` symbol ;)

**Comment by radare** [comment]
nope. that’s an ida-ism. r2 can grab this from RBin without having to analyze anything. rbin find symbols, imports, relocs and also if you are lucky determines where the main is located even if no symbols are found

**Comment by sferrini** [comment]
@radare great! Anyway, I've tried to use `e asm.bits=64` but it doesn't seems to solve the issue completely: https://asciinema.org/a/7ae4mfc48u61hg9y5163unwci at the end did you check the native 64 and native 32 bit regprofiles?

**Comment by radare** [comment]
yes, i know settings to 64bit is not the solution. i confirmed this was the issue but i was busy and didnt had time, maybe @skuater can find some time, if not i’ll give another try before the end of the week.

**Comment by skuater** [comment]
hi going to checkit

**Comment by sferrini** [comment]
@skuater thanks!

**Comment by radare** [comment]
Skuater found the problem and i did a quick hack to test it and fix the issue. It is now working as expected, but there's room for improvment in the implementation.

Thanks for reporting. It will be great if we can have a test in r2r

cc @Maijin

**Comment by Maijin** [comment]
or CC @sferrini can you provide test case in r2r to avoid it gets broken again since you have everything ready ?
