### ISSUE TITLE
Backward disasm seems broken

### ISSUE THREAD

**Issue by alvarofe** [radare/radare2#6805]
This binary

![w1_10](https://cloud.githubusercontent.com/assets/3474042/23044328/052a83e8-f4a0-11e6-93b1-5d491b5dbd39.png)

Load the binary with `r2 -B 0x360000 w1_10`

```
aaa
s 0x364d53
...
[0x00364d53]> so -1
[0x00364d52]> so -1
[0x00364c52]>
```

It should print a mov instruction as visual mode does. Moreover, with the second seek it moves 0x100 bytes.

**Comment by radare** [comment]
This was "fixed" by @skuater recently. Worth adding more tests and try reverting his commit to confirm

**Comment by skuater** [comment]
This issue is solved:
![imagen](https://cloud.githubusercontent.com/assets/8082461/23876402/a1ba73a2-083d-11e7-9cff-d6a40fa92ba1.png)

**Comment by alvarofe** [comment]
mm maybe is fixed in windows ?

```
[0x100072f6]> pd 4
            ;-- entry0:
            0x100072f6      cc             int3
/ (fcn) fcn.100072f7 88
|   fcn.100072f7 (int arg_ch);
|           ; arg int arg_ch @ ebp+0xc
|           0x100072f7      8bec           mov ebp, esp
|           0x100072f9      836d0c01       sub dword [ebp + arg_ch], 1
|       ,=< 0x100072fd      754a           jne 0x10007349
[0x100072f6]> s 0x100072fd
[0x100072fd]> so-1;pd 1
|           0x100072fb      0c01           or al, 1
```

**Comment by alvarofe** [comment]
ok fixed I mess up something. Thanks @skuater

**Comment by halos** [comment]
Just updated radare:
```$ r2 -v

radare2 1.2.0 14190 @ linux-x86-64 git.1.2.0-5-ga0d6e28
commit: a0d6e28aaaddfb05f1f7c656543dfbfd6cf8edac build: 2017-03-14
```

And still having the same issue in linux:

```
$ r2 -B 0x360000 w1_10

[0x00364d53]> pd 1
            0x00364d53      e846f4ffff     call 0x36419e
[0x00364d53]> so -1
[0x00364d52]> pd 1
            0x00364d52      cf             iretd
[0x00364d52]> # That should be a 'mov'. r2 only moved 1 byte backwards instead of 2
[0x00364d52]> so -1
[0x00364c52]> # Moved 0x100 bytes backwards from ...d52 to ...c52
```

**Comment by alvarofe** [comment]
Did you analyze the binary?

**Comment by halos** [comment]
Analyzing with `aaa` doesn't solve the problem. Same problems with both `so -1`

**Comment by alvarofe** [comment]
But your r2 version is not the actual master. Check with that please

**Comment by halos** [comment]
Now I have the correct version and it works like a charm
