### ISSUE TITLE
r2 -R cant step/continue

### ISSUE THREAD

**Issue by radare** [radare/radare2#7257]
```
$ echo program=/bin/ls > empty
$ r2 -R empty -d
Process with PID 53699 started...
= attach 53699 53699
bin.baddr 0x10b089000
Using 0x10b089000
asm.bits 64
 -- Nothing to see here. Move along.
[0x7fff62fbf000]> dc
[0x7fff62fbf000]> pd 2
            ;-- rip:
            0x7fff62fbf000      5f             pop  rdi
            0x7fff62fbf001      6a00           push 0
[0x7fff62fbf000]> ds
[0x7fff62fbf000]> pd 2
            ;-- rip:
            0x7fff62fbf000      5f             pop  rdi
            0x7fff62fbf001      6a00           push 0
[0x7fff62fbf000]>

```

**Comment by skuater** [comment]
on windows and linux work correctly:
![imagen](https://cloud.githubusercontent.com/assets/8082461/24955217/cab8a254-1f82-11e7-836b-efa36055ec82.png)

specific for mac?

**Comment by radare** [comment]
yeah seems to be a mac-specific issue

**Comment by alvarofe** [comment]
This is what I get 

```
mac:bin alvaro_fe$ ls|grep ls
ls
mac:bin alvaro_fe$ cat empty
program=~/bin/ls
mac:bin alvaro_fe$ sudo r2 -d -R empty
posix_spawnp: unknown error 2
posix_spawnp: Invalid argument
Child killed
ptrace: Cannot attach: Invalid argument
Possibly unsigned r2. Please see doc/osx.md
ERRNO: 22 (EINVAL)
Cannot open 'dbg://~/bin/ls' for writing.
```

I can't even open `ls` for debugging using -R

**Comment by radare** [comment]
Yep. This is mac only problem. Works fine on linux and windows

**Comment by alvarofe** [comment]
I wasted some hours to realize that ~/bin/ls is not valid in the program param, it should have been the whole path since posix_spawn fails :@. After fix that and using the same code to set up posix_spawn as normal debugging does, pid_to_task fails with KERN_FAILURE. Need to dig more

**Comment by alvarofe** [comment]
Fixed in local I have to cleanup.

**Comment by radare** [comment]
Seems not fixed according to the shy guy that only uses mail to report this

**Comment by utidevel** [comment]
it's still broken. Now all in / output goes to the stdio specified in the config file.

radare2 1.4.0 83 @ darwin-x86-64 git.1.4.0-21-g8e63cba
commit: 8e63cba29aed1f92faba2bcd60d749444e9e7e4d build: 2017-04-22__11:20:06

![screen shot 2017-04-22 at 11 37 01](https://cloud.githubusercontent.com/assets/27891772/25304788/79af6ea8-276e-11e7-8a3c-90aabb69d76e.png)
![screen shot 2017-04-22 at 11 37 59](https://cloud.githubusercontent.com/assets/27891772/25304790/8b12b45c-276e-11e7-90ed-7c1ea18cc15b.png)

**Comment by alvarofe** [comment]
I am about to commit a fix into master, it works for stdout and it should work as well with stdin, test it please to confirm before to close the issue.

![captura de pantalla 2017-04-28 a las 0 03 40](https://cloud.githubusercontent.com/assets/3474042/25506314/40fd39b4-2ba6-11e7-89d2-4a97cd927333.png)

odds are high that we are missing features from rarun that don't work for mac since is used posix instead of forking. So i would appreciate if you could test this thoroughly to make sure all the options are supported

**Comment by alvarofe** [comment]
I bet that stuff such as `!python blabla` commonly used for exploiting does not work here either.

**Comment by utidevel** [comment]
I tested
radare2 1.5.0-git 128 @ darwin-x86-64 git.1.4.0-66-gfae079d
commit: fae079d20cb0ce506f74104d2bce8ef3e4d61f3e build: 2017-04-28__07:53:21
Input output redirect seems to work fine now. Thank you :)
