### ISSUE TITLE
how different #!python is from a regular python shell

### ISSUE THREAD

**Issue by kamou** [radare/radare2#7515]
I am not sure if this is the right place to ask this question. If it's not just hit me with a stick and close this issue.

I'm trying to play with [Triton](https://github.com/JonathanSalwan/Triton) from rlang (#!python)
and it seems the behavior is quite not the same as if I played with it from a regular shell.

I'm just trying to disassemble a stupid instruction.
this is how I do it and what I get in a regular ipython shell:
```
In [1]: import triton                     
In [2]: triton.setArchitecture(triton.ARCH.X86_64)
In [3]: opcode = "\x55"               
In [4]:  inst = triton.Instruction() 
In [5]:  inst.setOpcodes(opcode)
In [6]:  inst.setAddress(0x1234)
In [7]: triton.disassembly(inst)
In [8]: print inst
0x1234: push rbp
```

now with r2's #!python:
```
In [1]: import triton                     
In [2]: triton.setArchitecture(triton.ARCH.X86_64)
In [3]: opcode = "\x55"               
In [4]:  inst = triton.Instruction() 
In [5]:  inst.setOpcodes(opcode)
In [6]:  inst.setAddress(0x1234)
In [7]: triton.disassembly(inst)
In [8]: print inst
0x1234: push
```
As you can see the disassembled instruction is not correct.
I'm not asking you to fix Triton or anything, just trying to understand what could lead to a different behavior.

**Comment by radare** [comment]
How many versions of python are installed on your system, which is the path of those imported modules, are all the same and the last version? Against which version do the rlang plugin was compiled? Against which version the r2api module was compiled for?

**Comment by radare** [comment]
anyway this seems to be a problem with triton, not r2

**Comment by kamou** [comment]
sorry, I was afk, The python versions are the same.
tracing with strace shows that both load the same triton module (only one available).
now regarding the r2api and rlang plugin it is the versions installed by r2pm. (I cleaned .config/radare2 today, and reinstalled lang-python today)
There is only one version of python available in my environment.
I'll continue investigating on Triton side if you believe this is a Triton issue.
Thanks.

**Comment by kamou** [comment]
ok narrowing down the issue, it lead me to capstone.
it seems like triton is not using the system wide capstone lib but the one provided / linked with r2 when launching it from rlang.
enabling CS_RELEASE flag in the root makefile make the issue disapear.
Should I investigate the problem further and provide another patch in capston-patches ?
Or do you have a better suggestion ?

**Comment by kamou** [comment]
Or couldn't there be a way for rlang to provide the symbols from the system wide capstone lib instead of the version r2 is linked against ?

**Comment by radare** [comment]
related https://github.com/radare/radare2/issues/7522

**Comment by radare** [comment]
R2 is built by default against capstone next from git

**Comment by radare** [comment]
R2lang doesnt honors env vars like python does. Do u have any special pythonpath?

**Comment by radare** [comment]
And r2 uses capstone statically linked so it shouldnt interfer wirh anything else

**Comment by kamou** [comment]
I do not have any specific pythonpath,
tested on both fresh fedora 25 and fresh debian 8 installs, and I had the same problem.
I've also instrumented my system wide capstone lib. And instrumentations do not appear when using triton inside r2lang.
furthermore, as I said, changing r2's capstone version through the CS_RELEASE flag fixes my problem.
So this is a bit confusing, it seems like triton inside rlang does actually use the statically linked capstone symbols. and not the system wide capstone solib symbols.

**Comment by radare** [comment]
capstone symbols are not stripped when statically linking, so maybe thats why triton is resolving the capstone symbols from there instead of the system. this is a bug in triton and not r2. they are linking in the wrong way. anyway i plan to hide all those symbols soon or late to speedup loading times and reduce public symbols

**Comment by kamou** [comment]
yes, just tested a breakpoint on cs_disasm, I ended up in libr_anal.so.

I am trying to figure out what is wrong on Triton side as well, but I am sorry if my questions are stupid, but:

I tried strip --strip-unneeded --strip-all on that same file (libr_anal.so), but the symbol was still there. as if it was actually exported.
and looking at it further with readelf, I see this:

```
readelf -s libr/anal/libr_anal.so | grep cs_disasm
  1250: 000000000019a978    72 FUNC    GLOBAL DEFAULT   12 cs_disasm_ex
  2078: 000000000019aae7   964 FUNC    GLOBAL DEFAULT   12 cs_disasm_iter
  2127: 000000000019a278  1792 FUNC    GLOBAL DEFAULT   12 cs_disasm
  8381: 000000000019aae7   964 FUNC    GLOBAL DEFAULT   12 cs_disasm_iter
  8456: 000000000019a278  1792 FUNC    GLOBAL DEFAULT   12 cs_disasm
  8661: 000000000019a978    72 FUNC    GLOBAL DEFAULT   12 cs_disasm_ex
```
if the capstone symbols were only statically linked, shouldn't they just disapear with the strip command ?

**Comment by kamou** [comment]
This might be more explicit with the --dyn-sym option:
```
readelf --dyn-syms libr/anal/libr_anal.so | grep cs_disasm
: 000000000019a978    72 FUNC    GLOBAL DEFAULT   12 cs_disasm_ex
  2078: 000000000019aae7   964 FUNC    GLOBAL DEFAULT   12 cs_disasm_iter
  2127: 000000000019a278  1792 FUNC    GLOBAL DEFAULT   12 cs_disasm
```

**Comment by radare** [comment]
All symbols not starting with r_ should be stripped out. There's a plan to do that before 1.5, lets see if i can have time to do it

**Comment by radare** [comment]
please try again, i think we got it fixed in master

**Comment by kamou** [comment]
still not good:
```
$ readelf --dyn-syms libr/anal/libr_anal.so | grep cs_disasm
  1250: 000000000019aeab    72 FUNC    GLOBAL DEFAULT   12 cs_disasm_ex
  2078: 000000000019b01a   964 FUNC    GLOBAL DEFAULT   12 cs_disasm_iter
  2126: 000000000019a7ab  1792 FUNC    GLOBAL DEFAULT   12 cs_disasm

```

tracing radare2 with gdb and setting a breakpoint on cs_disasm shows me that a call to `triton.disassembly(inst)`  from rlang gets me in libr_anal.so

**Comment by XVilka** [comment]
Can be this closed?

**Comment by radare** [comment]
Why not

**Comment by kamou** [comment]
sorry for the (very) late answer, still not working

**Comment by kamou** [comment]
```
~/D/d/radare2 ❯❯❯ nm ./libr/asm/libr_asm.so | grep cs_
0000000000a12ac0 d cs_arch_disallowed_mode_mask
0000000000a12b00 d cs_arch_init
0000000000a12b60 d cs_arch_option
000000000048632d T cs_close
0000000000486aec T cs_disasm
00000000004871ec T cs_disasm_ex
000000000048735b T cs_disasm_iter
00000000004860a8 T cs_errno
0000000000487234 T cs_free
00000000004877b3 T cs_group_name
00000000004877fd T cs_insn_group
0000000000487769 T cs_insn_name
00000000004872a5 T cs_malloc
0000000000a12bc8 D cs_mem_calloc
0000000000a12bd8 D cs_mem_free
0000000000a12bc0 D cs_mem_malloc
0000000000a12bd0 D cs_mem_realloc
0000000000487a21 T cs_op_count
0000000000486192 T cs_open
0000000000487e9f T cs_op_index
000000000048668b T cs_option
000000000048771f T cs_reg_name
00000000004878b4 T cs_reg_read
00000000004883cf T cs_regs_access
000000000048796a T cs_reg_write
0000000000488742 T cs_snprintf
00000000004886e3 T cs_strdup
00000000004860cf T cs_strerror
000000000048603a T cs_support
0000000000486005 T cs_version
0000000000a12be0 D cs_vsnprintf
00000000004683ee T r_asm_mnemonics_byname
```

**Comment by kamou** [comment]
```
libr/anal/libr_anal.so:
   427: 00000000003dbb66  1792 FUNC    GLOBAL DEFAULT   11 cs_disasm
   563: 00000000003dc266    72 FUNC    GLOBAL DEFAULT   11 cs_disasm_ex
   695: 00000000003dc3d5   964 FUNC    GLOBAL DEFAULT   11 cs_disasm_iter
libr/asm/libr_asm.so:
   370: 00000000004871ec    72 FUNC    GLOBAL DEFAULT   11 cs_disasm_ex
   375: 000000000048735b   964 FUNC    GLOBAL DEFAULT   11 cs_disasm_iter
   857: 0000000000486aec  1792 FUNC    GLOBAL DEFAULT   11 cs_disasm
```

**Comment by kamou** [comment]
libr_anal and libr_asm still export capstone symbols

**Comment by kamou** [comment]
reading the docs I found reference to the -fvisibility=hidden option + use of __attribute__((visibility("default")))
the first one, will set all symbols to be hidden, the latter will only make some apis visible
maybe that could help ?

**Comment by kamou** [comment]
seems like it is already done in r2..... I really have absolutely no clue why capstone symbols are still visible..

**Comment by kamou** [comment]
I think I found the problem, will do a PR

**Comment by radare** [comment]
🎉

**Comment by kamou** [comment]
(two years later) this issue can be closed now.
